### ISSUE TITLE
why does the balance query take two currencies in the url?

### ISSUE THREAD

**Issue by npomfret** [coinfloor/API#21]
The example url in the account balance documentation is this: https://webapi.coinfloor.co.uk:8090/bist/XBT/GBP/balance/

Why are there two currencies?  Can I add more?  Can I specify only one? 

Also, the docs states that I need these 3 parameters:

```
User ID - user ID
API key - api key
Passphrase - passphrase
```

That's not correct, is it?

**Comment by whitslack** [comment]
> Why are there two currencies? Can I add more? Can I specify only one?

It's because BIST is an emulation of Bitstamp's v1 API. Bitstamp traded only a single currency pair at that time, so their API did not support arbitrary numbers of currencies. When we implemented BIST, we had to replicate Bitstamp's API at multiple base URIs, one for each currency pair traded on Coinfloor. We don't recommend using BIST, as it's inefficient compared to our native WebSocket-based API.

> Also, the docs states that I need these 3 parameters: […] That's not correct, is it?

The docs are correct. What is your doubt?

**Comment by whitslack** [comment]
The `GetBalances` method in the WebSocket API returns all of your balances across all assets. With the JavaScript client library you would call this method like `Coinfloor.getBalances(console.log)`, replacing `console.log` with your own callback function to receive the balances. There is no plain HTTP API method to get all balances at once.
